'use client'
import ThemeRegistry from '~/app/UI/Theme'
import NavBar from '~/app/Navbar'

const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}


const RootLayout = ({ children }) => {
  return (
    <html lang="en">
      <head>
        <title>{metadata.title}</title>
        <meta name="description" content={metadata.description} />
        {/* TODO link para poner imagen */}
        {/* <link rel="icon" type="image/svg+xml" href={logo_blue} /> */}
      </head>
      <ThemeRegistry>
        <body>
          <NavBar />
          {children}
        </body>
      </ThemeRegistry>
    </html>
  )
}

export default RootLayout